/* Coast Tapas & Grill — menü verisi (baked / varsayılan).
   index.html anında bunu gösterir; admin panelinden yapılan değişiklikler
   Supabase venue_sites (slug: coast-menu) üzerine yazılır ve üstüne biner. */
window.COAST_SLUG = 'coast-menu';
window.COAST_NAME = 'Coast Tapas & Grill';

window.COAST_UI = {
  tr:{ allergy:"Herhangi bir yiyeceğe alerjiniz varsa, lütfen sipariş vermeden önce servis personelimizi bilgilendiriniz.",
       made:"Hepsi sevgiyle hazırlandı", legend:["Gluten","Kabuklular","Yumurta","Balık","Süt Ürünleri","Kuru Yemişler","Hardal","Susam","Yumuşakçalar","Vejetaryen"] },
  en:{ allergy:"If you have any food allergies, please inform our service staff before ordering.",
       made:"All Made With Love", legend:["Gluten","Crustaceans","Eggs","Fish","Dairy","Tree Nuts","Mustard","Sesame","Molluscs","Vegetarian"] }
};

window.COAST_MENU = [
 { id:"cold", tr:"Soğuklar", en:"Cold Tapas", items:[
   {tr:{n:"Guacamole",d:"Ezilmiş avokado, kırmızı soğan, taze kişniş, acı kırmızı biber ve lime ile hazırlanır. Çıtır mısır tortilla cipsi ile servis edilir."},en:{n:"Guacamole",d:"Freshly mashed avocado combined with red onions and red chili peppers. Infused with fresh coriander and a zesty squeeze of lime, served with crispy corn tortilla chips."},p:650,k:290},
   {tr:{n:"Çilek & Burrata",d:"Taze çilek, nane, mercanköşk ve fesleğen yaprakları, narenciye aromalı zeytinyağı ile buluşan burrata peyniri."},en:{n:"Strawberries Burrata",d:"Strawberries, fresh mint, marjoram, fresh basil leaves, citrus oil."},p:1050,k:350},
   {tr:{n:"Tiradito Peruano",d:"Narenciye ile marine edilmiş ince dilim levrek. Leche de Tigre sosu, avokado, yeşil acı biber ve kırmızı soğan ile servis edilir."},en:{n:"Tiradito Peruano",d:"Sliced sea bass fillet delicately cured in citrus juices, served with a vibrant Leche de Tigre sauce. Accompanied by diced avocado, spicy green chilies, and slivered red onions."},p:850,k:220},
   {tr:{n:"Şakşuka",d:"Patlıcan, patates ve biberin domates sosu ve zeytinyağı ile hazırlanan klasik soğuk meze."},en:{n:"Shakshuka",d:"Fried aubergine, potatoes and peppers served with olive oil and a rich tomato sauce."},p:600,k:180},
   {tr:{n:"Tataki de Res",d:"Mühürlenmiş dana bonfile, yuzu ponzu sosu, siyah sarımsak püresi, turşulanmış kırmızı soğan ve pırasa konfisi ile servis edilir."},en:{n:"Tataki de Res",d:"Seared premium beef tenderloin sliced rare, drizzled with a zesty yuzu ponzu sauce. Enhanced with a rich black garlic purée, tangy pickled onions, sesame and melt-in-the-mouth leek confit."},p:1050,k:250},
   {tr:{n:"Ton Balığı Tartar",d:"Taze ton balığı tartarı, avokado, acılı chili mayonez, premium tobiko ve çıtır nori ile hazırlanır."},en:{n:"Tuna Tartare",d:"Fresh tuna tartare with avocado dice, infused with spicy chili mayo. Finished with premium tobiko and accompanied by crunchy nori."},p:950,k:270},
   {tr:{n:"Humus",d:"Kornişon turşusu, toz kırmızı biber ve kendi bahçemizden natürel sızma zeytinyağı ile servis edilir."},en:{n:"Hummus",d:"With pickled cucumber, paprika, and olive oil from our garden."},p:500,k:340},
   {tr:{n:"Girit Usulü Çıtır Kabak",d:"Çıtır kızarmış kabak, Ezine peyniri ve taze fesleğenli yoğurt ile servis edilir."},en:{n:"Cretan Crispy Zucchini",d:"Fried zucchini crisps served over a yogurt dip prepared with Ezine cheese and fresh basil."},p:550,k:300},
   {tr:{n:"Yavaş Pişirilmiş Pancar",d:"Fırınlanmış pancar, yoğurt, pekan cevizi ve natürel sızma zeytinyağı ile servis edilir."},en:{n:"Slow Cooked Beetroot",d:"Slow-roasted beetroot slices served with yogurt, pecan nuts, and olive oil from our garden."},p:600,k:240},
   {tr:{n:"Zengin",d:"Elde doğranmış domates, taze soğan ve ceviz; biber salçası, nar ekşisi ve natürel sızma zeytinyağı ile hazırlanır. Kızarmış ekmek ile servis edilir."},en:{n:"Zengin",d:"Hand-chopped tomatoes, fresh scallions, and walnuts infused with Anatolian pepper paste, authentic pomegranate molasses, and extra virgin olive oil. Served with toasted bread."},p:550,k:290}
 ]},
 { id:"hot", tr:"Sıcaklar", en:"Hot Tapas", items:[
   {tr:{n:"Gambas al Ajillo",d:"Sarımsaklı tereyağında sotelenmiş karides, renkli biberler ve pastırma ile hazırlanır."},en:{n:"Gambas al Ajillo",d:"Prawns and pastrami sautéed with bell peppers in a flavorful garlic butter sauce."},p:1050,k:350},
   {tr:{n:"Bal & Zencefilli Tavuk Kanatları",d:"Bal, taze zencefil ve soya sosuyla marine edilip fırınlanan tavuk kanatları. Ev yapımı tatlı chili sosu ve taze coleslaw ile servis edilir."},en:{n:"Honey-Ginger Chicken Wings",d:"Oven-roasted chicken wings marinated in honey, ginger, and soy sauce. Tossed in homemade sweet chili sauce and served with fresh coleslaw."},p:800,k:510},
   {tr:{n:"Sarımsaklı Izgara Ahtapot",d:"Izgara ahtapot, ezilmiş baby patates ve sarımsak aromalı acı biber yağı ile servis edilir."},en:{n:"Garlic Charred Octopus",d:"Octopus with crushed baby potatoes, served with garlic chili oil."},p:1200,k:420},
   {tr:{n:"Taco con Carne",d:"Baharatlı chili con carne, taco tortilla, guacamole ve ekşi krema ile servis edilir."},en:{n:"Taco con Carne",d:"Spicy con carne served with taco tortillas, guacamole, and sour cream."},p:800,k:510},
   {tr:{n:"Popcorn Karides",d:"Çıtır kaplamalı karides, coleslaw, hafif acılı chipotle mayonez, susam ve taze soğan ile servis edilir."},en:{n:"Popcorn Shrimps",d:"Crispy shrimps, coleslaw, light chili chipotle mayo, sesame, spring onion."},p:800,k:340},
   {tr:{n:"Tortillas de Papa",d:"Chorizo ile doldurulmuş kızarmış patates lokmaları, ev yapımı chimichurri sos eşliğinde servis edilir."},en:{n:"Tortillas de Papa",d:"Golden-fried potato balls filled with rich chorizo, accompanied by fresh home-made chipotle, served with chimichurri."},p:800,k:400},
   {tr:{n:"İsli Patlıcan Milanesa",d:"Odun ateşinde közlenmiş bütün patlıcan, çıtır panko kaplamasıyla kızartılır. Sarımsaklı yoğurt ve taze otlu chimichurri sos ile tamamlanır."},en:{n:"Smoked Aubergine Milanesa",d:"Whole fire-roasted aubergine, lightly bruised and coated in crispy panko. Finished with a swirl of creamy garlic yogurt and a vibrant herb chimichurri drizzle."},p:750,k:390},
   {tr:{n:"Empanada",d:"Dana etli harç ile doldurulmuş empanada, ev yapımı chimichurri sos ile servis edilir."},en:{n:"Empanada",d:"Stuffed with beef, served with chimichurri."},p:750,k:390},
   {tr:{n:"Frito Misto di Mare",d:"Çıtır kalamar, karides ve midye; kavrulmuş susam ve taze soğan ile servis edilir. Yanında kimchi mayonez eşlik eder."},en:{n:"Frito Misto di Mare",d:"Crispy calamari, prawns and mussels, topped with toasted sesame seeds and fresh scallions. Served with a side of kimchee mayo."},p:1050,k:470},
   {tr:{n:"Çıtır Kabak Çiçeği Tempura",d:"Peynir mus ile doldurulmuş kabak çiçekleri, hafif tempura hamurunda kızartılarak servis edilir."},en:{n:"Crispy Stuffed Pumpkin Flower Tempura",d:"Delicate pumpkin flowers filled with a rich cheese mousse, fried in a light and crispy tempura batter."},p:750,k:300},
   {tr:{n:"Tacos",d:"İki farklı taco birlikte: biri karides ve ekşi krema, diğeri didiklenmiş dana eti ve Ezine peyniri. Chipotle mayonez ve aioli sos ile tamamlanır."},en:{n:"Tacos",d:"Two tacos served together: one with shrimp and tangy sour cream, and the other with tender pulled beef topped with crumbled Ezine cheese. Enhanced with chipotle mayo and aioli sauces."},p:800,k:490},
   {tr:{n:"Pimientos de Padrón",d:"Zeytinyağında közlenmiş Padrón biberleri, ekşi krema ile servis edilir."},en:{n:"Pimientos de Padrón",d:"Roasted with olive oil, served with sour cream and lemon zest."},p:600,k:170},
   {tr:{n:"Çıtır Kalamar",d:"Klasik tartar sos ile servis edilir."},en:{n:"Fried Calamari",d:"Served with tartar sauce."},p:900,k:450},
   {tr:{n:"Patatas Bravas Alaturka",d:"Çıtır patates küpleri; tatlı-ekşi ve hafif acılı domates sosu ile hazırlanır. Üzeri yoğurt ile tamamlanır."},en:{n:"Patatas Bravas Alaturka",d:"Crispy golden potato cubes topped with sweet & spicy tomato sauce. Finished with a cool drizzle of creamy yogurt."},p:600,k:430}
 ]},
 { id:"salads", tr:"Salatalar", en:"Salads", items:[
   {tr:{n:"The Green Bloom",d:"Akdeniz yeşillikleri, kavrulmuş çam fıstığı, yeşil elma ve narenciye sos ile hazırlanır."},en:{n:"The Green Bloom",d:"Mixed fresh mediterranean greens, roasted pine-nuts, green apple, citrus dressing."},p:600,k:280},
   {tr:{n:"Coast Tomatoes Salad",d:"Lures Garden'dan özenle seçilen domatesler, Ezine peynir musu, taze fesleğen, kendi üretimimiz natürel sızma zeytinyağı ve Maldon deniz tuzu ile servis edilir."},en:{n:"Coast Tomatoes Salad",d:"Lures Garden's tomatoes, Ezine cheese mousse, fresh basil, our own extra virgin olive oil, Maldon."},p:600,k:300},
   {tr:{n:"Mediterranean Quinoa Salad",d:"Kinoa, közlenmiş avokado dilimleri, Finike portakalı, Akdeniz yeşillikleri ve frambuaz sirkesi sosu ile hazırlanır."},en:{n:"Mediterranean Quinoa Salad",d:"Roasted sliced avocado, Finike orange segments, Mediterranean mixed fresh greens, raspberry vinegar sauce."},p:700,k:310},
   {tr:{n:"Summer Breeze",d:"Közlenmiş mevsim taş meyveleri, çırpılmış ricotta peyniri ve tatlı kiraz domatesi. Taze nane yaprakları ve hafif narenciye ile tamamlanır."},en:{n:"Summer Breeze",d:"Charred seasonal stone fruits, soft whipped ricotta, and sweet cherry tomatoes. Finished with torn mint leaves and a light citrus drizzle."},p:900,k:270}
 ]},
 { id:"pasta", tr:"Makarna & Risotto", en:"Pasta & Risotto", items:[
   {tr:{n:"Istakoz Kuyruklu Linguine",d:"Şarap ile lezzetlendirilen istakoz kuyruğu, uzun süre pişirilmiş yoğun domates sosuyla harmanlanan linguine üzerinde servis edilir. Cherry domates ve taze fesleğen ile tamamlanır."},en:{n:"Lobster Tail Linguine",d:"Succulent wine-glazed lobster tail served over linguine tossed in a rich, slow-simmered tomato sauce. Finished with sweet cherry tomatoes and fragrant fresh basil leaves."},p:2050,k:540},
   {tr:{n:"Casarecce Pesto Rosso",d:"Casarecce makarna, ev yapımı kremamsı kırmızı pesto sosu ve Grana Padano peyniri ile hazırlanır. Kavrulmuş kırık fındık ile tamamlanır."},en:{n:"Casarecce Pesto Rosso",d:"Casarecce pasta tossed in a rich, creamy house-made red pesto sauce, enriched with authentic Grana Padano cheese. Finished with a crunchy topping of toasted, crumbled hazelnuts."},p:950,k:670},
   {tr:{n:"Spaghetti Carbonara",d:"Klasik spaghetti, yumurta sarısı ve Grana Padano peyniri ile hazırlanan carbonara sosunda harmanlanır. Çıtır Türk pastırması ile servis edilir."},en:{n:"Spaghetti Carbonara",d:"Classic spaghetti coated in a velvety egg yolk and Grana Padano reduction, finished with savory bites of crispy Turkish pastrami."},p:1100,k:710},
   {tr:{n:"Kuşkonmazlı Risotto",d:"Arborio pirinci ile hazırlanan kremamsı risotto, Grana Padano peyniri ve taze kuşkonmaz ile zenginleştirilir. Blanşe edilmiş kuşkonmaz ile tamamlanır."},en:{n:"Asparagus Risotto",d:"Velvety Arborio risotto enriched with Grana Padano and fresh asparagus, topped with crisp blanched asparagus for a perfect textural contrast."},p:1100,k:530},
   {tr:{n:"Spaghetti all'Aglio e Olio",d:"Spaghetti, kendi üretimimiz natürel sızma zeytinyağı, aromatik sarımsak ve taze acı biber ile hazırlanır."},en:{n:"Spaghetti all'Aglio e Olio",d:"Classic spaghetti tossed in our house-pressed, estate-grown olive oil, infused with aromatic garlic and a fiery kick of fresh chili peppers."},p:750,k:490},
   {tr:{n:"Risotto di Mare",d:"Domates aromalı kremamsı Arborio risotto, Grana Padano peyniri ile zenginleştirilir. Karides, kalamar ve taze midye ile servis edilir."},en:{n:"Risotto di Mare",d:"Velvety tomato-infused Arborio risotto enriched with Grana Padano, tossed with a premium medley of prawns, calamari, and fresh mussels."},p:1700,k:640}
 ]},
 { id:"grills", tr:"Izgaralar", en:"Grills", items:[
   {tr:{n:"Zarandeado (2 Kişilik)",d:"Kelebek şeklinde açılmış bütün çipura, odun ateşinde ızgaralanır. İsli Meksika adobo sosu ve chimichurri ile lezzetlendirilir, taze mikro filizlerle tamamlanır."},en:{n:"Zarandeado (for two)",d:"Flame-grilled, butterflied whole sea bream generously brushed with smoky Mexican adobo sauce and chimichurri. Finished with a delicate topping of fresh micro greens."},p:2300,k:700},
   {tr:{n:"Odun Ateşinde Kuzu Sırt",d:"Ev yapımı teriyaki glaze, fondant patates, odun ateşinde pişirilmiş pırasa ve Bergama tulum peyniri sos ile servis edilir."},en:{n:"Open-Fire Lamb Loin",d:"Homemade teriyaki glaze, fondant potatoes, wood-fired leek, and fresh aromatic herbs with Bergama Tulum cheese sauce."},p:1800,k:780},
   {tr:{n:"Camarones al Ajillo",d:"Sarımsaklı yağda pişirilmiş jumbo karides; chorizo ve parmesan cipsi, mikro filizler, baby patates ve közlenmiş domates ile servis edilir."},en:{n:"Camarones al Ajillo",d:"King prawns cooked with garlic oil, accompanied with chorizo parmesan crisp, micro greens, baby potatoes and roasted tomatoes."},p:1900,k:500},
   {tr:{n:"Izgara Antrikot",d:"Odun ateşinde ızgaralanmış antrikot, salsa verde ve taze otlu chimichurri ile servis edilir. Izgara mısır, közlenmiş pırasa ve baharatlı ızgara baby patates eşlik eder."},en:{n:"Grilled Entrecôte",d:"Flame-grilled entrecôte sliced and drizzled with a zesty salsa verde and vibrant herb chimichurri. Served with grilled corn on the cob, coal-roasted leeks, and seasoned grilled baby potatoes."},p:1750,k:720},
   {tr:{n:"Harissa Tavuk",d:"Acılı Harissa sosu, taze otlu tereyağlı arpa şehriye, ufalanmış Ezine peyniri, kırmızı soğan turşusu, fırınlanmış tatlı patates."},en:{n:"Harissa Chicken",d:"Spicy Harissa sauce, fresh herb buttered orzo, crumbled Ezine cheese, pickled red onion, roasted sweet potato."},p:1250,k:600},
   {tr:{n:"Anticucho Peruano",d:"Peru baharatlarıyla marine edilmiş tavuk but şiş; domatesli pilav, baharatlı patates, baby pırasa ve mısır ile servis edilir."},en:{n:"Anticucho Peruano",d:"Chicken thigh skewers with spices served with tomato rice, spiced potatoes, spiced baby leek and corn."},p:1400,k:600},
   {tr:{n:"Dana Bonfile",d:"Izgara dana bonfile, chili-balzamik sos, ev yapımı kalın kesim patates kızartması ve mevsim sebzeleri ile servis edilir."},en:{n:"Fillet Steak",d:"Fillet steak, home-made thick cut chips and seasonal sautéed vegetable, served with chili-balsamic or creamy mushroom sauce."},p:1900,k:710}
 ]},
 { id:"signature", tr:"İmza Lezzetler", en:"Signature", items:[
   {tr:{n:"Dana Yanak",d:"Kök sebzeler ve aromatik otlarla ağır ağır pişirilmiş dana yanak. Trüf aromalı Ödemiş Sarı Kız patates püresi, yoğun demi-glace sos ve çıtır dukkah ile servis edilir."},en:{n:"Slow-Braised Beef Cheek",d:"Beef cheek infused with root vegetables and aromatics. Served with truffle-scented Ödemiş 'Sarı Kız' potato mash, rich demi-glace sauce, and crunchy dukkah crisps."},p:1600,k:690},
   {tr:{n:"Bal & Hardal Soslu Izgara Somon",d:"Odun ateşinde ızgaralanmış somon fileto, imza bal-hardal sosumuz ile hazırlanır. Ezilmiş rustik patates, ızgara kuşkonmaz ve taze mikro filizlerle servis edilir."},en:{n:"Honey Mustard Grilled Salmon",d:"Flame-grilled salmon fillet glazed with our signature honey mustard sauce. Accompanied by coarse-mashed rustic potatoes, grilled asparagus, and delicate micro greens."},p:1450,k:550},
   {tr:{n:"Kayseri Yağlama",d:"Geleneksel Kayseri Yağlamasının modern yorumu. Kat kat lavaş ekmeği ve özel baharatlı dana kıyması, sarımsaklı yoğurt ile servis edilir."},en:{n:"Kayseri Yağlama",d:"A modern touch on a traditional dish, consisting of layers of lavash bread and ground beef, topped with garlic yogurt."},p:1400,k:690},
   {tr:{n:"Kaya Levreği",d:"Tavada çıtır pişirilmiş Kaya levreği, beyaz şarap ve kapari sos ile tamamlanır. Sote havuç, baby patates, kuşkonmaz ve bezelye eşliğinde servis edilir."},en:{n:"Rock Bass",d:"Crispy pan-seared rock bass fillet, finished with a refined white wine and caper reduction. Served alongside a colorful sautéed medley of carrots, baby potatoes, asparagus, and sweet pea."},p:1400,k:430},
   {tr:{n:"Cordero al Limón / Limonlu Kuzu",d:"Orta İspanya'nın klasik lezzetlerinden biri. Limon ve taze biberiye ile uzun süre pişirilmiş kuzu kol, baharatlı kırmızı pirinç pilavı ve sıcak taco tortilla ile servis edilir."},en:{n:"Cordero al Limón — Lamb with Lemon",d:"A classic specialty from central Spain. Tender lamb shoulder slow-cooked with lemon and fresh rosemary. Served alongside spiced red rice and warm taco tortillas."},p:1800,k:700}
 ]},
 { id:"sides", tr:"Yan Lezzetler", en:"Side Orders", items:[
   {tr:{n:"Kalın Kesim Patates Kızartması",d:"Ev yapımı kalın kesim patates kızartması."},en:{n:"Thick Cut Chips",d:""},p:400,k:300},
   {tr:{n:"Sotelenmiş Mevsim Sebzeleri",d:"Mevsimin taze sebzeleri ile hazırlanır."},en:{n:"Sautéed Seasonal Vegetables",d:""},p:400,k:110},
   {tr:{n:"Fırınlanmış Tatlı Patates",d:"Fırında pişirilmiş tatlı patates."},en:{n:"Oven Baked Sweet Potatoes",d:""},p:400,k:170},
   {tr:{n:"Patates Püresi",d:"Kremamsı patates püresi."},en:{n:"Mashed Potatoes",d:""},p:400,k:190},
   {tr:{n:"Coleslaw Salatası",d:"Klasik lahana ve havuç salatası."},en:{n:"Coleslaw",d:""},p:300,k:160}
 ]},
 { id:"desserts", tr:"Tatlılar", en:"Desserts", items:[
   {tr:{n:"Tiramisu",d:"Ev yapımı kedi dili bisküvileri, yoğun Robusta espresso ile ıslatılır. Gerçek vanilya ile aromalandırılmış günlük hazırlanmış mascarpone kreması ile kat kat sunulur."},en:{n:"Tiramisu",d:"Home-made ladyfingers delicately soaked in a bold Robusta espresso reduction. Layered with a velvety, daily-whipped mascarpone cream infused with real vanilla bean."},p:650,k:460},
   {tr:{n:"Churros",d:"Meksika usulü kızartılmış çıtır churros. Ev yapımı çikolata sosu ve gerçek vanilyalı dondurma ile servis edilir."},en:{n:"Churros",d:"Authentic Mexican-style churros, fried until golden and crisp. Served with our signature house-made chocolate sauce and a scoop of artisanal vanilla bean ice cream."},p:550,k:500},
   {tr:{n:"Pavlova",d:"Dışı kıtır, içi yumuşak beze; hafif vanilyalı krema, çilek salsa ve mevsim meyveleri ile servis edilir."},en:{n:"Pavlova",d:"A delicate, crispy-edged meringue with a soft marshmallow center, topped with a velvety layer of soft vanilla cream. Finished with a vibrant strawberry salsa and a medley of fresh seasonal berries."},p:700,k:330},
   {tr:{n:"Damask Dessert",d:"Ev yapımı pekmez ile tatlandırılmış, tarçın aromalı rafine irmik keki. İmza yoğurt ganajı ve taze portakal kabuğu rendesi ile tamamlanır."},en:{n:"Damask Dessert",d:"A refined Middle Eastern semolina cake sweetened with artisanal homemade molasses and infused with warm cinnamon. Served with our signature housemade yogurt ganache and finished with fresh orange zest."},p:500,k:550},
   {tr:{n:"Bitter Çikolatalı Turta",d:"%70 bitter çikolata ve öğütülmüş badem ile hazırlanan yoğun çikolatalı torte. Ev yapımı çikolata ganajı ve taze frambuaz ile servis edilir."},en:{n:"Dark Chocolate Torte",d:"A rich, flourless-style torte crafted with 70% dark chocolate and ground almonds, bound with delicate breadcrumbs. Layered with our signature housemade chocolate ganache and served with fresh, tart raspberries."},p:650,k:490}
 ]}
];
